services:
  - type: web
    name: tcs-bfsi-highlights
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y wget gnupg unzip curl
      ./install_chrome.sh
      pip install -r requirements.txt
    startCommand: streamlit run trial.py --server.port=$PORT --server.address=0.0.0.0
